### ISSUE TITLE
[question] Define ManagePackageVersionsCentrally in other files

### ISSUE THREAD

**Issue by balteravishay** [balteravishay/scorecard#10]
When exploring [this repo](https://github.com/microsoft/sbom-tool) we notice that ManagePackageVersionsCentrally is defined in [Directory.Build.props](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/Directory.Build.props) file instead of in Directory.Packages.props as documented [here](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#enabling-central-package-management).
should this be supported/expected behaviour?

**Comment by JonDouglas** [comment]
this is supported behavior. Really any .props file is okay by MSBuild but we encourage people to use `Directory.packages.props` file as more features are detecting that file. 

I think we ought to only check for the latter for CPM because we'd want people to move to the proper file rather than the old ways/hacks they are using still.

**Comment by aortiz-msft** [comment]
> this is supported behavior. Really any .props file is okay by MSBuild but we encourage people to use `Directory.packages.props` file as more features are detecting that file.
> 
> I think we ought to only check for the latter for CPM because we'd want people to move to the proper file rather than the old ways/hacks they are using still.

+1 to this.
